baseurl: https://mshepherd.gitlab.io/riemannhypothesis.info/

archetypeDir: archetypes
assetDir: assets
contentdir: content
dataDir: data
layoutdir: layouts
publishdir: public
staticDir: static
themesDir: themes

title: Understanding the Riemann Hypothesis
canonifyurls: true

DefaultContentLanguage: en
theme: beautifulhugo
metaDataFormat: yaml
pygmentsUseClasses: true
pygmentCodeFences: true
# disqusShortname: recommend-games
# googleAnalytics: UA-128891980-1
enableRobotsTXT: true

Params:
  subtitle: Everything You Always Wanted to Know About Primes (But Were Afraid to Ask)
  mainSections:
    - post
    - posts
  logo: logo.png
  favicon: favicon.ico
  dateFormat: January 2, 2006
  commit: false
  rss: true
  comments: true
  # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"
  # gcse: 013480686921635014344:zokjfkkzyza
  readingTime: true
  wordCount: true
  useHLJS: true
  socialShare: true
  showRelatedPosts: true

Author:
  name: Markus Shepherd
  email: markus@recommend.games
  facebook: markus.r.shepherd
  # googleplus: +username # or xxxxxxxxxxxxxxxxxxxxx
  gitlab: mshepherd
  github: MarkusShepherd
  twitter: MarkusRShepherd
  reddit: MarkusShepherd
  linkedin: markusschepke
  # xing: username
  stackoverflow: users/2634131/markus-shepherd
  # snapchat: username
  instagram: funny_monkey_42
  youtube: user/MarkusSchepke # or channel/channelname
  # soundcloud: username
  # spotify: username
  # bandcamp: username
  # itchio: username
  # keybase: username

menu:
  main:
    - name: About
      identifier: about
      weight: 10
    - name: About the blog
      parent: about
      url: about/
      weight: 10
    - name: About me
      parent: about
      url: about-me/
      weight: 20

    - name: Projects
      identifier: projects
      url: projects/
      weight: 20
    - name: Recommend.Games
      parent: projects
      url: recommend-games/
      weight: 10
    - name: Diris
      parent: projects
      url: diris/
      weight: 20
    - name: Mathematical papers
      parent: projects
      url: mathematical-papers/
      weight: 30
    - name: Ricochet Robots solver
      parent: projects
      url: ricochet-robots-solver/
      weight: 40
    - name: TeXCVMaker
      parent: projects
      url: texcvmaker/
      weight: 50

    - name: Recommended books
      identifier: books
      url: books/
      weight: 30

    # - name: Tags
    #   url: tags/
    #   weight: 50
    # - name: Categories
    #   url: categories/
    #   weight: 60

sitemap:
  changefreq: weekly
