baseurl: http://riemannhypothesis.info/

archetypeDir: archetypes
assetDir: assets
contentdir: content
dataDir: data
layoutdir: layouts
publishdir: public
staticDir: static
themesDir: themes

title: Understanding the Riemann Hypothesis
canonifyurls: false

DefaultContentLanguage: en
theme: twentyfourteen
metaDataFormat: yaml
pygmentsUseClasses: true
pygmentCodeFences: true
# disqusShortname: recommend-games
# googleAnalytics: UA-128891980-1
enableRobotsTXT: true

Params:
  subtitle: Everything You Always Wanted to Know About Primes (But Were Afraid to Ask)
  mainSections:
    - post
    - posts
  # logo: logo.png
  # favicon: favicon.ico
  dateFormat: January 2, 2006
  commit: false
  rss: true
  comments: true
  # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"
  # gcse: 013480686921635014344:zokjfkkzyza
  readingTime: true
  wordCount: true
  useHLJS: true
  socialShare: true
  showRelatedPosts: true

Author:
  name: Markus Shepherd
  email: markus@recommend.games
  # facebook: markus.r.shepherd
  # googleplus: +username # or xxxxxxxxxxxxxxxxxxxxx
  # gitlab: recommend.games
  # github: recommend-games
  # twitter: recommend_games
  # reddit: MarkusShepherd
  # linkedin: markusschepke
  # xing: username
  # stackoverflow: users/2634131/markus-shepherd
  # snapchat: username
  # instagram: funny_monkey_42
  # youtube: user/MarkusSchepke # or channel/channelname
  # soundcloud: username
  # spotify: username
  # bandcamp: username
  # itchio: username
  # keybase: username

menu:
  main:
    # - name: Recommend.Games
    #   url: https://recommend.games/#/
    #   weight: 10
    - name: Blog
      url: ''
      weight: 20
    - name: About
      url: page/about/
      weight: 30
    - name: Tags
      url: tags
      weight: 40

sitemap:
  changefreq: weekly
